# Shall I notify people of a LibsDisguises update?
NotifyUpdate: true

# The disguise plugin stores all GameProfiles inside a file called 'cache.yml'
# This means that the plugin doesn't need to constantly call Mojang just to find a skin for an offline player
# However some people may prefer to disable this.
# Even if you disable this, if there was disguises in the cache already then it will use them
SaveGameProfiles: true

# This option is useless if you don't enable SaveGameProfiles!
# If a player has been disguised before and their skin saved into the cache
# When they join the server will automatically update the cache incase they changed their skin
UpdateGameProfiles: true

# THIS IS A PREMIUM ONLY FEATURE. TO USE IT, PURCHASE THE PLUGIN.
# Saves disguises so that they persist after server shutdown, chunks unload, player logouts and so on.
# As such, this completely replaces the KeepDisguises aspect which has been removed except for the player death.
# Players - Are player disguises saved
# Entities - Are entities disguises saved (This is everything that's not a player)
# If you are using the dev builds, place your premium version of Lib's Disguises.jar inside the LibsDisguises folder
# This will enable premium only features for the dev builds.
# The saved disguises are saved in a json file format inside the plugin folder, there will be no other formats
SaveDisguises:
    Players: false
    Entities: false

# Does the player keep their disguise after they die?
KeepDisguises:
    PlayerDeath: false

# Should the plugin use translations? Note that a player must see the message before it will appear in translations.yml
Translations: false

# How should the plugin handle self disguises scoreboards? It disables pushing in whichever team they're assigned.
# If you want them to be able to push again when they undisguise, set this to CREATE_SCOREBOARD
# I have to disable pushing or you will be pushed around by your own self disguise
# MODIFY_SCOREBOARD - Modifies the player's current team if possible, otherwise assigns them to a new scoreboard team.
# IGNORE_SCOREBOARD - Doesn't touch scoreboards at all, effectively means that if you didn't disable pushing in their scoreboard team; They will still be pushed around
# CREATE_SCOREBOARD - Creates a new team which copies the attributes of their previous scoreboard team which they are then assigned to. This means they keep nametag color and other options.
SelfDisguisesScoreboard: MODIFY_SCOREBOARD

# More options incase you want to disable a specific setting of the scoreboard
Scoreboard:
  # Should it modify the scoreboard to turn collisions off?
  Collisions: true
  # Should it modify the scoreboard teams to disable seeing friendly invisibles?
  SeeFriendlyInvisibles: true

# Whats the permission to get the notification?
Permission: 'libsdisguises.update'

# Whats the max size allowed for command disguiseradius
DisguiseRadiusMax: 50

# Whats the max size allowed for command undisguiseradius
UndisguiseRadiusMax: 50

# Shall the players view their disguises?
# Best used when viewing yourself in 3rd person
ViewSelfDisguises: true

# Shall I disguise the sounds?
# This turns your damage sound into a MOOOO
DisguiseSounds: true

# Shall the disguised hear their disguise sounds or their damage sounds.
# I disable this as it can be a little confusing when not used with self disguises
HearSelfDisguise: true

# Shall I send the velocity packets? I REALLY recommend you don't disable.
# This is the only thing allowing the mobs to fly without glitching out.
SendVelocity: true

# For self disguises, they need to have the armor and the held item removed
# Else they see floating armor, floating held items.
# This turns the items invisible in the disguised players inventory. It does not actually remove them!
# Be warned that in creative this can actually delete the item from the inventory due to a weird bug
RemoveArmor: true
RemoveHeldItem: false

# If you set a disguise to burning, it will no longer be able to be shown as sneaking or invisible.
# Set this to true if you want the disguise to get the animations of the disguised entity. Such as invisible, on fire, sprinting, sneaking, blocking
# This is only valid if you set a animation on the disguise itself. Because the entitys animations are applied otherwise.
AddEntityAnimations: true

# When a sheep or wolf is right clicked with dye. The client automatically assumes it was successful and displays the sheeps wool or the wolfs collar as dyed.
# This is a option that either prevents that happening, or it changes their color officially in the plugin so that everyone sees it changed.
# Its currently set to false which means that the color is not changed and will refresh itself to the player.
# Please note that this will not remove the dye from their hands. This also does not check if the disguised entity is actually a sheep/wolf and wants a say in its color.
DyeableSheep: false
DyeableWolf: false

# This is only called into action when the disguise is constructed using the commands.
# And when the disguise supports that. This will not be used at all for plugins constructing the disguises for instance.
# Such as prophunt. Its also false because its kind of a retarded feature.
# This is pretty simple. It shows the players displayname (Name as it appears in chat) above their head.
# This also overrides any custom name they have set in their disguise options.
# This does not take effect on player disguises
ShowNamesAboveDisguises: false

# This supports the above option.
# If this is true, then the name shown above the head appears regardless of if you are looking at the disguise directly or not.
NameAboveHeadAlwaysVisible: true

# This modifys the bounding box, This is stuff like can a arrow hit them.
# If you turn this to true, arrows will act like they hit the disguise in the right place!
# So someone disguised as a enderdragon will easily get shot down by arrows!
# This WILL conflict with NoCheatPlus. Other plugins may also get problems.
# This shouldn't really be enabled for players as it also interferes with their movement because the server thinks the player is larger than he really is.
# That makes the player unable to approach this building because the server thinks he is trying to glitch inside blocks.
# This feature is highly experimental and is garanteed to cause problems for players who are disguised
ModifyBoundingBox: false

# This prevents disguised players from being targeted by monsters.
# This doesn't prevent their targeting you if already targeting when disguised
# They will just ignore you unless provoked.
MonstersIgnoreDisguises: false

# This works only for players, disguised monsters and the like will not be undisguised
# Should the player's disguises be removed if he attacks something?
BlowDisguisesWhenAttacking: false
# Should the player's disguises be removed if he's attacked by something?
BlowDisguisesWhenAttacked: false

#Stop shulker disguises from moving, they're weird. This option only effects PLAYERS that are disguised, other entities disguised as shulkers will NOT be effected!
StopShulkerDisguisesFromMoving: true

# A option to choose how many seconds a DisguiseEntity command is valid for people to right click a entity to disguise it before expiring
DisguiseEntityExpire: 10

# Another option to choose the same thing for DisguiseClone command
DisguiseCloneExpire: 10
# Max disguises to store at a time with the DisguiseClone command
DisguiseCloneSize: 3

# This controls if a entitys max health is determined by the entity, or by the disguise.
# Wither is 200, a player is 20. With this enabled, a player disguised as a wither will have the boss bar health accurate to the players health.
# Else it will be 1/20 of the boss bar when he is full health.
# Setting this in LivingWatcher overrides both values.
MaxHealthDeterminedByEntity: true

# This here is a option to turn off misc disguises.
# This means you can not have a living entity disguise as a non-living entity.
# This disables the Attributes packet, Non-living entities can still disguise as other non-living
# This means that the above option will not work as it uses the attribute packet.
MiscDisguisesForLiving: true

# Turn this to true to have players undisguised when switching worlds
UndisguiseOnWorldChange: false

# Contact Mojang's servers? Disabling this option will disable player skin disguises!
ContactMojangServers: true

# Hide players in tab when disguised? This means a disguised player cannot be seen when you press tab! This can be toggled on/off per disguise
HideDisguisedPlayersFromTab: false

# Always show player disguises in tab? The names will continue to appear in tab until the disguise is removed.
ShowPlayerDisguisesInTab: false

# Don't like players able to set themselves invisible when using the disguise commands? Toggle this to true and no one can use setInvisible! Plugins can still use this however.
DisableInvisibility: false

# This will help performance, especially with CPU
# Due to safety reasons, self disguises can never have their packets disabled.
PacketsEnabled:
    # This disables the animation packet. If a disguised entity sends a animation packet and they are using a non-living disguise. People will crash.
    # Disabling this also means that if a player disguised as a non-player leaves a bug. People will crash
    Animation: true
    # Disabling this means that you can't use the setSleeping option on a player disguise. Also you will crash anyone watching when you try to sleep in a bed if disguised as a non-player
    # This also sends a chunk packet at key positions else it doesn't work for 1.8. Lazyness means it does it for older versions too currently.
    Bed: true
    # This disguises the collect packet. If a living entity disguised as a non-living entity picks up a item. People will crash. This fixes it
    # This also fixes people crashing if a item disguised as a sleeping player is picked up - Only true if Bed is enabled as well
    Collect: true
    # This disables a fix for when a disguised entity wearing armor dies, if the disguise can wear armor. It drops unpickupable items to anyone watching.
    EntityStatus: true
    # Entity equipment is the packets that are sent to ensure that a disguise has or doesn't have armor, and their held item.
    # Disabling this means that any disguises which can wear armor or hold items will show the armor/held item that the disguised is wearing.
    Equipment: true
    # This doesn't actually disable the packet. It would introduce problems. Instead it does the next best thing and caches the data.
    # This means that entity metadata will not change, and will only be sent in the spawn packet.
    # This is good if performance is extremely in need.
    # This is bad to disable unless you are ONLY going to use the disguises for decorations.
    # To be honest. This is basically "Disable entity animations". That option is called 'AddEntityAnimations' in the config but unlike that, this is always in effect.
    # Animations set by use of the api or through the disguise command are still in effect.
    Metadata: true
    # Movement packets are the biggest cpu hit. These are majorly used to ensure that the disguises facing direction isn't bugged up.
    # If you are using the Item_Frame disguise, when a packet is sent (Roughly every 2min) the disguise will bug up until they move.
    Movement: true
    # Disable this if you don't mind crashing everytime you see someone riding something disguised as a non-living entity
    Riding: true
    # When disguised as a wither skull, it sends a look packet every tick so that the wither skull is facing the right way.
    WitherSkull: true