[versions]
com-mojang-authlib-old = "3.5.41"
com-mojang-authlib-new = "6.0.54"
commons-lang-commons-lang = "2.6"
io-netty-netty-buffer = "4.1.90.Final"
io-netty-netty-codec = "4.1.90.Final"
it-unimi-dsi-fastutil-version = "8.5.8"
com-mojang-datafixerupper = "7.0.14"

lombok-version = "1.18.34"
shadow-version = "8.1.1"
junit-version = "4.13.2"
junit-jupiter-version = "5.9.3"
mockito-version = "5.12.0"

net-kyori-adventure-api = "4.17.0"
com-retro-packetevents = "2.5.0-SNAPSHOT"
placeholder-api = "2.11.6"

bungeecord-chat = "1.16-R0.4"
org-spigotmc-spigot = "1.21-R0.1-SNAPSHOT"
io-papermc-paper-api = "1.21.1-R0.1-SNAPSHOT"


[libraries]
com-mojang-datafixerupper = { module = "com.mojang:datafixerupper", version.ref = "com-mojang-datafixerupper" }
com-mojang-authlib-old = { module = "com.mojang:authlib", version.ref = "com-mojang-authlib-old" }
com-mojang-authlib-new = { module = "com.mojang:authlib", version.ref = "com-mojang-authlib-new" }
commons-lang-commons-lang = { module = "commons-lang:commons-lang", version.ref = "commons-lang-commons-lang" }
io-netty-netty-buffer = { module = "io.netty:netty-buffer", version.ref = "io-netty-netty-buffer" }
it-unimi-dsi-fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "it-unimi-dsi-fastutil-version" }
io-netty-netty-codec = { module = "io.netty:netty-codec", version.ref = "io-netty-netty-codec" }
io-papermc-paper-paper-api = { module = "io.papermc.paper:paper-api", version.ref = "io-papermc-paper-api" }
net-kyori-adventure-api = { module = "net.kyori:adventure-api", version.ref = "net-kyori-adventure-api" }
net-kyori-adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "net-kyori-adventure-api" }
net-kyori-adventure-text-serializer-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "net-kyori-adventure-api" }
net-kyori-adventure-text-serializer-json = { module = "net.kyori:adventure-text-serializer-json", version.ref = "net-kyori-adventure-api" }
net-md-v5-bungeecord-chat = { module = "net.md-5:bungeecord-chat", version.ref = "bungeecord-chat" }
org-spigotmc-spigot = { module = "org.spigotmc:spigot", version.ref = "org-spigotmc-spigot" }
org-spigotmc-spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "org-spigotmc-spigot" }
com-retro-packetevents = { module = "com.github.retrooper:packetevents-spigot", version.ref = "com-retro-packetevents" }
org-projectlombok-lombok = { module = "org.projectlombok:lombok", version.ref = "lombok-version" }
junit-plugin = { module = "junit:junit", version.ref = "junit-version" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter-version" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito-version" }
placeholder-api = { module = "me.clip:placeholderapi", version.ref = "placeholder-api" }

[plugins]
shadowjar = { id = "com.github.johnrengelman.shadow", version.ref = "shadow-version" }

